version: '3.8'

services:
  app:
    build: .
    environment:
      - DISPLAY=${DISPLAY}
      - QT_QPA_PLATFORM=xcb
    volumes:
      - .:/app
      - /tmp/.X11-unix:/tmp/.X11-unix:ro
      - ${HOME}/.Xauthority:/home/appuser/.Xauthority:ro
    user: "1000:1000"
    network_mode: host 